Merge pull request #14998 from KevinGrandon/bug_956012_update_mobile_shims
Bug 956012 - Desktop b2g with local profile is trying to load the SIM / JavaScript error: conn.setVoicePrivacyMode is not a function
(cherry picked from commit fa66acd68ac739690b2b892997de5e43e9fe42e7)