Merge pull request #9335 from albertopq/contacts-fix-imgLoader-search
Bug 864095 - TypeError: loadImage is not a function r=crdlc (cherry picked from commit 59edecbac6f61d470e3ea0573f6b9e06ceb8c5ed)