Merge pull request #9170 from jmcanterafonseca/fix_trim
Bug 861707 - TypeError: contact.givenName[0].trim is not a function(cherry picked from commit 5169151672faa4040a4ad815667a519d8e631f07)